name: Continuous

on: 
  push:
  create:
    tags:

jobs:

  linux-mac:
    strategy:
      matrix:
        cfg: [{os: ubuntu-latest, cxx: g++-9},
              {os: macos-latest, cxx: clang++}]
        # config: [Release, Debug]
        config: [Release]

    runs-on:  ${{ matrix.cfg.os }}

    env:
      CXX: ${{ matrix.cfg.cxx }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DOSName=${{ matrix.cfg.os }}

    - name: Create archive
      run: tar -czvf bunin_${{ matrix.cfg.os }}.tar.gz build/entrypoint_exec_${{ matrix.cfg.os }} build/lib/*
    -
      name: Deploy
      uses: xresloader/upload-to-github-release@v1
      with:
        tags: true
        draft: false
        file: bunin_${{ matrix.cfg.os }}.tar.gz
        overwrite: false
        update_latest_release: true
        verbose: true


  windows-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build -DOSName=win

    - name: Release build
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Release run
      run: build/Release/entrypoint_exec_win.exe

    -
      name: Deploy
      uses: xresloader/upload-to-github-release@v1
      with:
        tags: true
        draft: false
        file: build/Release/entrypoint_exec_win.exe;
        overwrite: true
        update_latest_release: true
        verbose: true