name: Continuous

on:
  push:
  create:
    tags:

jobs:

  linux-mac:
    strategy:
      matrix:
        cfg: [{os: ubuntu-latest, cxx: g++-9},
              {os: macos-latest, cxx: clang++}]
        # config: [Release, Debug]
        config: [Release]

    runs-on:  ${{ matrix.cfg.os }}

    env:
      CXX: ${{ matrix.cfg.cxx }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DOSName=${{ matrix.cfg.os }}

      - name: CMake Build
        run: cmake --build build --parallel

      - name: Run executable - entrypoint_exec
        run: build/entrypoint_exec_${{ matrix.cfg.os }} path=mesh/catorus.geogram

      - name: Run executable - triToQuad
        run: build/triToQuadSimple_exec_${{ matrix.cfg.os }}

      - name: Create archive
        run: tar -czvf bunin_${{ matrix.cfg.os }}.tar.gz build/entrypoint_exec_${{ matrix.cfg.os }} build/lib/*

      - name: Create archive 2
        run: tar -czvf bunin_${{ matrix.cfg.os }}.tar.gz build/triToQuadSimple_exec_${{ matrix.cfg.os }} build/lib/*
      -
        name: Deploy
        uses: xresloader/upload-to-github-release@v1
        with:
          tags: true
          draft: false
          file: bunin_${{ matrix.cfg.os }}.tar.gz
          overwrite: false
          update_latest_release: true
          verbose: true


  windows-msvc:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B build -DOSName=win

      - name: Release build
        run: cmake --build build --parallel --config Release

      - name: Release run - entrypoint_exec
        run: build/Release/entrypoint_exec_win.exe path=mesh/catorus.geogram

      - name: Release run - triToQuadSimple_exec
        run: build/Release/triToQuadSimple_exec_win.exe

      - name: Debug build
        run: cmake --build build --parallel --config Debug

      - name: Debug run - entrypoint_exec
        run: build/Debug/entrypoint_exec_win.exe

      - name: Debug run - triToQuadSimple_exec
        run: build/Debug/triToQuadSimple_exec_win.exe

      -
        name: Deploy
        uses: xresloader/upload-to-github-release@v1
        with:
          tags: true
          draft: false
          file: build/Release/entrypoint_exec_win.exe;
          overwrite: true
          update_latest_release: true
          verbose: true

      -
        name: Deploy 2
        uses: xresloader/upload-to-github-release@v1
        with:
          tags: true
          draft: false
          file: build/Release/triToQuadSimple_exec_win.exe;
          overwrite: true
          update_latest_release: true
          verbose: true